#
# PRE DEPLOYMENT
#

# Install the MidoNet dependencies
- role:
  - primary-controller
  - controller
  - compute
  - nsdb
  - midonet-gw
  - midonet-analytics
  stage: pre_deployment
  type: shell
  requires:
  - post_deployment_start
  required_for:
  - post_deployment_end
  id: install_midonet_puppet_modules
  parameters:
    cmd: bash install_midonet_puppet_modules.sh
    timeout: 1440

# Override neutron params
- role:
  - primary-controller
  - controller
  - compute
  - nsdb
  - midonet-gw
  - midonet-analytics
  requires:
  - post_deployment_start
  required_for:
  - post_deployment_end
  type: puppet
  id: override_hiera
  parameters:
    puppet_manifest: puppet/manifests/midonet-override-hiera.pp
    puppet_modules: "puppet/modules/:/etc/puppet/modules/"
    timeout: 1440


#
# GROUPS
#
- id: nsdb
  parameters:
    strategy:
      type: parallel
  requires:
  - deploy_start
  required_for:
  - controller
  - primary-controller
  - deploy_end
  role:
  - nsdb
  type: group
  tasks:
  - logging
  - hiera
  - setup_repositories
  - fuel_pkgs
  - globals
  - tools
  - logging
  - netconfig-midonet

- id: midonet-gw
  parameters:
    strategy:
      type: parallel
  required_for:
  - deploy_end
  requires:
  - nsdb
  role:
  - midonet-gw
  tasks:
  - logging
  - hiera
  - globals
  - netconfig-midonet
  type: group

- id: midonet-analytics
  parameters:
    strategy:
      type: parallel
  required_for:
  - deploy_end
  requires:
  - nsdb
  role:
  - midonet-analytics
  tasks:
  - logging
  - hiera
  - globals
  - netconfig-midonet
  type: group

#
# DEPLOYMENT
#

- id: netconfig-midonet
  parameters:
    puppet_manifest: /etc/puppet/modules/osnailyfacter/modular/netconfig/netconfig.pp
    puppet_modules: /etc/puppet/modules
    timeout: 3600
    cwd: /
  required_for:
  - netconfig
  requires:
  - tools
  groups:
  - /.*/
  type: puppet
  version: 2.0.0

# First independent tasks
- id: setup_repositories_midonet
  groups:
  - primary-controller
  - controller
  - compute
  - nsdb
  - midonet-gw
  - midonet-analytics
  required_for:
  - deploy_end
  requires:
  - netconfig
  type: puppet
  parameters:
    puppet_manifest: puppet/manifests/midonet-define-repositories.pp
    puppet_modules: "puppet/modules/:/etc/puppet/modules/"
    timeout: 1440

- id: enable_ip_forward_midonet
  groups:
  - compute
  - controller
  - primary-controller
  - midonet-gw
  required_for:
  - deploy_end
  requires:
  - deploy_start
  type: puppet
  parameters:
    puppet_manifest: puppet/manifests/midonet-enable-ip-forward.pp
    puppet_modules: "puppet/modules/:/etc/puppet/modules/"
    timeout: 720

# NSDB-only tasks
- id: zookeeper_and_cassandra_midonet
  groups:
  - nsdb
  required_for:
  - deploy_end
  requires:
  - setup_repositories_midonet
  - firewall
  type: puppet
  reexecute_on:
  - deploy_changes
  parameters:
    puppet_manifest: puppet/manifests/midonet-nsdb.pp
    puppet_modules: "puppet/modules/:/etc/puppet/modules/"
    timeout: 1440
