#
# GROUPS
#
- id: nsdb
  parameters:
    strategy:
      type: parallel
  requires:
  - deploy_start
  required_for:
  - controller
  - primary-controller
  - deploy_end
  role:
  - nsdb
  type: group
  tasks:
  - logging
  - hiera
  - setup_repositories
  - fuel_pkgs
  - globals
  - tools
  - logging
  - netconfig-midonet

- id: midonet-gw
  parameters:
    strategy:
      type: parallel
  required_for:
  - deploy_end
  requires:
  - nsdb
  role:
  - midonet-gw
  tasks:
  - logging
  - hiera
  - globals
  - netconfig-midonet
  type: group

- id: midonet-analytics
  parameters:
    strategy:
      type: parallel
  required_for:
  - deploy_end
  requires:
  - nsdb
  role:
  - midonet-analytics
  tasks:
  - logging
  - hiera
  - globals
  - netconfig-midonet
  type: group

#
# DEPLOYMENT
#

- id: netconfig-midonet
  parameters:
    puppet_manifest: /etc/puppet/modules/osnailyfacter/modular/netconfig/netconfig.pp
    puppet_modules: /etc/puppet/modules
    timeout: 3600
    cwd: /
  required_for:
  - netconfig
  requires:
  - tools
  groups:
  - /.*/
  type: puppet
  version: 2.0.0

# First independent tasks
- id: setup_repositories_midonet
  groups:
  - primary-controller
  - controller
  - compute
  - nsdb
  - midonet-gw
  - midonet-analytics
  required_for:
  - deploy_end
  requires:
  - netconfig
  type: puppet
  parameters:
    puppet_manifest: puppet/manifests/midonet-define-repositories.pp
    puppet_modules: "puppet/modules/:/etc/puppet/modules/"
    timeout: 1440

- id: enable_ip_forward_midonet
  groups:
  - compute
  - controller
  - primary-controller
  - midonet-gw
  required_for:
  - deploy_end
  requires:
  - deploy_start
  type: puppet
  parameters:
    puppet_manifest: puppet/manifests/midonet-enable-ip-forward.pp
    puppet_modules: "puppet/modules/:/etc/puppet/modules/"
    timeout: 720

# NSDB-only tasks
- id: zookeeper_and_cassandra_midonet
  groups:
  - nsdb
  required_for:
  - deploy_end
  requires:
  - setup_repositories_midonet
  - firewall
  type: puppet
  reexecute_on:
  - deploy_changes
  parameters:
    puppet_manifest: puppet/manifests/midonet-nsdb.pp
    puppet_modules: "puppet/modules/:/etc/puppet/modules/"
    timeout: 1440

# PRE-NEUTRON CONFIGURATION
- id: deploy_cluster_midonet
  groups:
  - primary-controller
  - controller
  required_for:
  - deploy_end
  - openstack-network-start
  requires:
  - setup_repositories_midonet
  - enable_ip_forward_midonet
  - firewall
  - primary-cluster-haproxy
  - cluster-haproxy
  type: puppet
  reexecute_on:
  - deploy_changes
  parameters:
    puppet_manifest: puppet/manifests/midonet-install-cluster.pp
    puppet_modules: "puppet/modules/:/etc/puppet/modules/"
    timeout: 1440

# In controllers, we have to install midolman 'before' the neutron
# configuration, because subnet creates a the DHCP port in neutron
# and we need to do the binding.
- id: agent-midonet-controller
  groups:
  - primary-controller
  - controller
  required_for:
  - deploy_end
  - openstack-network-start
  requires:
  - deploy_cluster_midonet
  type: puppet
  parameters:
    puppet_manifest: puppet/manifests/midonet-install-agent.pp
    puppet_modules: "puppet/modules/:/etc/puppet/modules/"
    timeout: 1440

# NEUTRON CONFIGURATION
- id: openstack-network-midonet-replace-service-name
  groups:
  - primary-controller
  - controller
  requires:
  - openstack-network-common-config
  required_for:
  - openstack-network-end
  type: puppet
  parameters:
    puppet_manifest: puppet/manifests/midonet-replace-guess-func.pp
    puppet_modules: "puppet/modules/:/etc/puppet/modules/"
    timeout: 1440

- id: openstack-network-midonet-config
  groups:
  - primary-controller
  - controller
  requires:
  - openstack-network-midonet-replace-service-name
  required_for:
  - openstack-network-server-config
  type: puppet
  parameters:
    puppet_manifest: puppet/manifests/midonet-neutron-configure.pp
    puppet_modules: "puppet/modules/:/etc/puppet/modules/"
    timeout: 1440

- id: openstack-network-midonet-networks
  groups:
  - primary-controller
  requires:
  - openstack-network-server-config
  required_for:
  - openstack-network-end
  type: puppet
  parameters:
    puppet_manifest: puppet/manifests/midonet-neutron-networks.pp
    puppet_modules: "puppet/modules/:/etc/puppet/modules/"
    timeout: 1440

- id: openstack-network-midonet-compute-nova
  parameters:
    puppet_manifest: puppet/manifests/midonet-compute-nova.pp
    puppet_modules: "puppet/modules/:/etc/puppet/modules/"
    timeout: 1440
  required_for:
  - openstack-network-end
  requires:
  - openstack-network-common-config
  - openstack-network-agents-l3
  - openstack-network-agents-metadata
  type: puppet
  groups:
  - compute


# Skipped tasks
- id: openstack-network-server-config
  type: skipped
- id: openstack-network-networks
  type: skipped
- id: openstack-network-routers
  type: skipped
- id: openstack-network-plugins-l2
  type: skipped
- id: primary-openstack-network-plugins-l2
  type: skipped
- id: openstack-network-agents-l3
  type: skipped
- id: primary-openstack-network-agents-l3
  type: skipped
- id: openstack-network-compute-nova
  type: skipped
- id: netconfig
  type: skipped

# POST-DEPLOYMENT TASKS

# The task configure_default_route reinstalls openvswitch-switch
# and removes midolman. This task only runs on compute hosts, so
# we have to make sure that midolman is installed 'after' the
# 'configure_default_route' task has run.
# It also installs it on Gateway nodes
- id: agent-midonet-compute
  role:
  - compute
  - midonet-gw
  required_for:
  - post_deployment_end
  requires:
  - configure_default_route
  type: puppet
  reexecute_on:
  - deploy_changes
  parameters:
    puppet_manifest: puppet/manifests/midonet-install-agent.pp
    puppet_modules: "puppet/modules/:/etc/puppet/modules/"
    timeout: 1440

- id: tunnel-zones-midonet
  role:
  - compute
  - controller
  - primary-controller
  - midonet-gw
  required_for:
  - post_deployment_end
  requires:
  - agent-midonet-compute
  type: puppet
  parameters:
    puppet_manifest: puppet/manifests/midonet-host-registry.pp
    puppet_modules: "puppet/modules/:/etc/puppet/modules/"
    timeout: 720

- id: rootwrap-midonet
  role:
  - compute
  - controller
  - primary-controller
  - midonet-gw
  required_for:
  - post_deployment_end
  requires:
  - agent-midonet-compute
  type: puppet
  parameters:
    puppet_manifest: puppet/manifests/midonet-ensure-rootwrap.pp
    puppet_modules: "puppet/modules/:/etc/puppet/modules/"
    timeout: 720

- id: gateway-midonet
  role:
  - midonet-gw
  requires:
  - tunnel-zones-midonet
  required_for:
  - post_deployment_end
  type: puppet
  parameters:
    puppet_manifest: puppet/manifests/midonet-gateway-bgp.pp
    puppet_modules: "puppet/modules/:/etc/puppet/modules/"
    timeout: 720
