# Install the MidoNet dependencies
- id: install_dep
  role:
  - primary-controller
  - controller
  - compute
  - nsdb
  - midonet-gw
  - midonet-analytics
  type: shell
  requires: [pre_deployment_start,hiera,setup_repositories,fuel_pkgs]
  required_for: [pre_deployment_end]
  version: 2.0.0
  parameters:
    cmd: bash install_midonet_puppet_modules.sh
    timeout: 1440

# Override neutron params
- id: neutron-override
  role:
  - primary-controller
  - controller
  - compute
  - nsdb
  - midonet-gw
  - midonet-analytics
  type: puppet
  requires: [pre_deployment_start,hiera,setup_repositories,fuel_pkgs]
  required_for: [pre_deployment_end]
  version: 2.0.0
  parameters:
    puppet_manifest: puppet/manifests/midonet-override-hiera.pp
    puppet_modules: "puppet/modules/:/etc/puppet/modules/"
    timeout: 1440
